apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: chainsaw
  timeouts:
    apply: 120s
    assert: 400s
    cleanup: 120s
    delete: 240s
    error: 120s
    exec: 200s
  # skipDelete: true
  failFast: true
  parallel: 1
