
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: /etc/http-proxy.conf
      containerPath: /etc/systemd/system/containerd.service.d/http-proxy.conf
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.71.37:10809"]
      endpoint = ["http://192.168.71.37:10809"]
